{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "[2023-01-25 22:18:32,053] ERROR in app: Exception on /chatbot [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\maxer\\AppData\\Roaming\\Python\\Python39\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\maxer\\AppData\\Local\\Temp\\ipykernel_14928\\603551764.py\", line 34, in chatbot\n",
      "    pergunta = request.args('pergunta')\n",
      "TypeError: 'ImmutableMultiDict' object is not callable\n",
      "127.0.0.1 - - [25/Jan/2023 22:18:32] \"GET /chatbot?pergunta=quem%20é%20barack%20obama HTTP/1.1\" 500 -\n",
      "[2023-01-25 22:18:44,918] ERROR in app: Exception on /chatbot [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\maxer\\AppData\\Roaming\\Python\\Python39\\site-packages\\flask_cors\\extension.py\", line 165, in wrapped_function\n",
      "    return cors_after_request(app.make_response(f(*args, **kwargs)))\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"c:\\ProgramData\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\maxer\\AppData\\Local\\Temp\\ipykernel_14928\\603551764.py\", line 34, in chatbot\n",
      "    pergunta = request.args('pergunta')\n",
      "TypeError: 'ImmutableMultiDict' object is not callable\n",
      "127.0.0.1 - - [25/Jan/2023 22:18:44] \"GET /chatbot?pergunta=quem%20é%20barack%20obama HTTP/1.1\" 500 -\n"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request, jsonify\n",
    "from flask_cors import CORS, cross_origin\n",
    "import openai\n",
    "\n",
    "app = Flask(__name__)\n",
    "CORS(app, resources={r\"/chatbot/*\":{\"origins\":\"http://localhost\"}})\n",
    "\n",
    "openai.api_key = \"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\"\n",
    "\n",
    "def mychat(prompt):\n",
    "    \n",
    "    response = openai.Completion.create(\n",
    "        model=\"text-davinci-003\",\n",
    "        prompt=prompt,\n",
    "        max_tokens=2048\n",
    "    )\n",
    "    return response.choices[0].text\n",
    "\n",
    "\n",
    "def mydraw(prompt):\n",
    "\n",
    "    response = openai.Image.create(\n",
    "        size=\"512x512\",\n",
    "        prompt=prompt,\n",
    "        n=1,\n",
    "        response_format=\"url\"\n",
    "\n",
    "    )\n",
    "    return response[\"data\"][0][\"url\"]\n",
    "\n",
    "@cross_origin\n",
    "@app.route('/chatbot')\n",
    "def chatbot():\n",
    "        pergunta = request.args('pergunta')\n",
    "        if pergunta[0:4] == 'img:':\n",
    "           pergunta=pergunta.replace('img:', '')\n",
    "           resposta = mydraw(pergunta)\n",
    "           return jsonify(url_imagem=resposta, resposta='')\n",
    "        else:\n",
    "            resposta = mychat(pergunta)\n",
    "            return jsonify(resposta=resposta)\n",
    "\n",
    "app.run()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "ad2bdc8ecc057115af97d19610ffacc2b4e99fae6737bb82f5d7fb13d2f2c186"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
